version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest
additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg ~/.ansible.cfg

dependencies:
  galaxy:
    collections:
      - name: fortinet.fortios
      - name: ansible.netcommon
      - name: ansible.utils
      - name: ansible.posix
      - name: community.general
  python:
    - pyats[library]
    - genie
    - ansible-pylibssh
