- name: Aplicar políticas al FortiGate desde Git
  gather_facts: no
  hosts: "{{ _hosts }}"
  connection: httpapi
  roles:
    - role: firewall_policy
      vars:
        policy_file: "{{ _policy }}"