---
- name: Load policy file
  ansible.builtin.include_vars:
    file: '{{_policy_file}}.yml'
    name: policy_data

- name: Configure global attributes
  hosts: "{{ _hosts }}"
  connection: httpapi
  tasks:
   - name: Configure Fortinet Firewall Policy
     fortinet.fortios.fortios_firewall_policy:
      vdom: root 
      state: "present"
      firewall_policy: "{{ policy_data.firewall_policy }}"