---
- name: Configure global attributes
  hosts: "{{ _hosts }}"
  connection: httpapi
  gather_facts: false
  tasks:
   - name: Configure Fortinet Firewall Hostname
     fortinet.fortios.fortios_system_global:
        vdom:  "root"
        system_global:
            hostname: "{{ _hostname }}"
