---
- name: Configure global attributes
  hosts: "{{ _hosts }}"
  connection: httpapi
  tasks:
   - name: Configure Fortinet Firewall Hostname
     fortinet.fortios.fortios_system_global:
       enable_log: true
       vdom: root
       system_global:
         hostname: "{{ _hostname }}"
     register: resultado

   - name: Mostrar resultado
     debug:
       var: resultado
