---
- name: Configure global attributes
  hosts: "{{ _hosts }}"
  connection: httpapi
  tasks:
   - name: Configure Fortinet Firewall Policy
     fortinet.fortios.fortios_firewall_policy:
      vdom: root  #"{{ _vdom }}"
      state: "present"
      firewall_policy:
        policyid: 1
        q_origin_key: 1
        status: enable
        name: Mypolicy
        action: accept
        srcintf:
        - name: port1
          q_origin_key: port1
        dstintf:
        - name: port1
          q_origin_key: port1
        srcaddr:
          - name: login.windows.net
            q_origin_key: login.windows.net
        dstaddr:
          - name: all
            q_origin_key: all
        service:
          - name: HTTP
            q_origin_key: HTTP