---
- name: Configure global attributes
  hosts: "{{ _hosts }}"
  gather_facts: false
  tasks:
   - name: Configure Fortinet Firewall Hostname
     fortios_system_global:
        vdom:  "{{ _vdom | default('root') }}"
        system_global:
            hostname: "{{ _hostname }}"
