- name: Test connection to Fortinet firewall
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping the Fortinet firewall
      fortios_system_facts:
        host: "{{ _hosts }}"
        vdom: "root"