- name: Test connection to Fortinet firewall
  hosts: all
  connection: httpapi
  gather_facts: false
  tasks:
  - name: fetch all firewall addresses
    fortinet.fortios.fortios_configuration_fact:
      selector: firewall_address
