- name: Test connection to Fortinet firewall
  hosts: all
  gather_facts: false
  tasks:
  - name: fetch all firewall addresses
    fortios_configuration_fact:
      selector: firewall_address
  - name: Ping the Fortinet firewall
    fortios_configuration_fact:
      vdom: "root"
      selector: system_status