- name: Test connection to Fortinet firewall
  hosts: all
  connection: httpapi
  gather_facts: false
  tasks:
  - name: fetch all firewall addresses
    fortinet.fortios.fortios_configuration_fact:
      selector: firewall_address
  - name: Ping the Fortinet firewall
    fortinet.fortios.fortios_configuration_fact:
      vdom: "root"
      selector: system_status
  - name: change local time fortinet firewall
